***  Testing Log
LocalErrorHandler called from main, x = 1.000000

***  Testing Throw
LocalErrorHandler exception in main, file `TestError.C' line 13
throw exception
Caught LocalErrorHandler exception

***  Testing ABORT
Abort in main, file `TestError.C' line 22
x = 2.000000

